name: Validate
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: setup.py
      - name: Install dependencies
        run: pip install .
      - name: Run tests
        run: python -m unittest
